import type { WPTesterConfig, ResolvedWPTesterConfig, ResolvedEnvironment } from "@wp-tester/config";
import {
  resolveConfig,
  parseBootstrapPath,
  hostToVfs,
  resolveAbsolute,
} from "@wp-tester/config";
import type { Report } from "@wp-tester/results";
import { EMPTY_REPORT, mergeReports, StreamingReporter, TeamCityParser } from "@wp-tester/results";
import { startPlayground } from "@wp-tester/runtime";
import { mountWordPressTestLibrary } from "./wordpress-test-lib";
import { access } from "fs/promises";

export function shouldRunPhpUnitTests(config: WPTesterConfig): boolean {
  return config.tests?.phpunit !== undefined;
}

/**
 * Run PHPUnit tests in WordPress Playground environment for a specific environment
 *
 * @param config - Resolved test configuration
 * @param environment - Environment configuration
 * @param hostPhpunitConfigPath - Absolute path to PHPUnit config on host
 * @param streamingReporter - Optional streaming reporter for real-time output
 * @returns CTRF report with test results
 */
async function runPhpUnitTestsForEnvironment(
  config: ResolvedWPTesterConfig,
  environment: ResolvedEnvironment,
  hostPhpunitConfigPath: string,
  streamingReporter?: StreamingReporter
): Promise<Report> {
  const testMode = config.tests.phpunit!.testMode;

  let phpUnitEnvironmentVariables: Record<string, string> = {};
  let environmentWithMount: ResolvedEnvironment = environment;

  // Prepare environment with WordPress test library for unit tests only
  // Integration tests use standard WordPress installation via wp-load.php
  if (testMode === "unit") {
    environmentWithMount = await mountWordPressTestLibrary(environment);
    phpUnitEnvironmentVariables = {
      WP_TESTS_DIR: "/tmp/wordpress-tests-lib",
    };
  }

  // Start playground with all mounts and steps including test library initialization
  const runtime = await startPlayground(environmentWithMount);
  const playground = runtime.playground;

  if (config.reporters && config.reporters.includes("default")) {
    const modeLabel =
      testMode === "unit"
        ? "unit tests (with WordPress test library)"
        : "integration tests (with WordPress)";
    console.log(
      `Running PHPUnit ${modeLabel} for environment: ${environment.name}`
    );
  }

  try {
    // Determine the plugin or theme being tested
    if (!config.projectType) {
      console.error(
        "Project type must be specified in config for PHPUnit tests"
      );
      return EMPTY_REPORT;
    }

    if (!config.projectVFSPath) {
      console.error(
        `Project type '${config.projectType}' does not support PHPUnit tests`
      );
      return EMPTY_REPORT;
    }

    // Map host PHPUnit config path to VFS
    const vfsPhpunitConfigPath = hostToVfs(hostPhpunitConfigPath, config);

    // Only create WordPress bootstrap in integration mode
    let bootstrapFilePath: string | null = null;
    if (testMode === "integration") {
      // Parse bootstrap path from PHPUnit config and map to VFS
      const bootstrapPath = await parseBootstrapPath(hostPhpunitConfigPath);
      // Determine bootstrap file path in the playground filesystem
      let userBootstrap = `${config.projectVFSPath}/tests/bootstrap.php`; // Default fallback
      if (bootstrapPath) {
        // Bootstrap path from parseBootstrapPath is relative, convert to absolute
        const absoluteBootstrapPath = resolveAbsolute(
          bootstrapPath,
          config.projectHostPath
        );
        userBootstrap = hostToVfs(absoluteBootstrapPath, config);
      }

      // Create a custom bootstrap file that loads WordPress, then user's bootstrap if it exists
      bootstrapFilePath = `/tmp/wp-tester-bootstrap.php`;
      await playground.writeFile(
        bootstrapFilePath,
        `<?php
      // Auto-generated by wp-tester - loads WordPress then user's bootstrap

      // 1. Load WordPress
      if (file_exists('/wordpress/wp-load.php')) {
        require_once '/wordpress/wp-load.php';
      }
      // 2. Load user's bootstrap file if it exists
      if (!empty('${userBootstrap}') && file_exists('${userBootstrap}')) {
        require_once '${userBootstrap}';
      }
      `
      );
    }

    // Build PHP CLI arguments with environment variables
    // Use TeamCity format for streaming output
    const cliArgs = [
      "php",
      "-d",
      // Set variables_order to EGPCS to ensure environment variables are accessible.
      // This is required for WordPress test library to access WP_TESTS_DIR via getenv().
      // Default PHP settings often exclude 'E' (Environment), which would break test setup.
      "variables_order=EGPCS",
      `${config.projectVFSPath}/vendor/bin/phpunit`,
      "-c",
      vfsPhpunitConfigPath,
      "--teamcity", // Use TeamCity format for streaming
    ];

    // Override bootstrap file with our custom one (only in integration mode)
    if (bootstrapFilePath !== null) {
      cliArgs.push("--bootstrap", bootstrapFilePath);
    }

    // Create a local streaming reporter if one wasn't provided
    const useStreaming = config.reporters?.includes("default") ?? true;
    const reporter = streamingReporter || new StreamingReporter();

    // Configure reporter based on config
    if (!useStreaming) {
      reporter.setEnabled(false);
    }

    // Create TeamCity parser connected to the reporter
    const parser = TeamCityParser.withReporter(reporter);

    // Run PHPUnit tests
    const result = await playground.cli(cliArgs, {
      env: phpUnitEnvironmentVariables,
    });

    // Process stdout with TeamCity parser for streaming results
    // Stderr is still piped to console for error messages
    const textDecoder = new TextDecoder();
    await Promise.all([
      result.stdout.pipeTo(
        new WritableStream({
          write(chunk) {
            const text = textDecoder.decode(chunk, { stream: true });
            parser.write(text);
          },
          close() {
            parser.flush();
          },
        })
      ),
      result.stderr.pipeTo(
        new WritableStream({
          write(chunk) {
            // Only show stderr if streaming is enabled
            if (useStreaming) {
              process.stderr.write(chunk);
            }
          },
        })
      ),
    ]);

    const exitCode = await result.exitCode;

    if (exitCode !== 0 && exitCode !== 1 && exitCode !== 2) {
      // Exit code 1 indicates test failures, exit code 2 indicates errors - both are acceptable
      console.error(`PHPUnit exited with code ${exitCode}`);
      return EMPTY_REPORT;
    }

    // Get the report from the streaming reporter
    const report = reporter.getReport();

    // Update tool name with environment
    report.results.tool.name = `wp-tester-phpunit (${environment.name})`;

    return report;
  } catch (error) {
    console.error(
      `Error running PHPUnit tests for environment "${environment.name}":`,
      error
    );
    return EMPTY_REPORT;
  } finally {
    // Cleanup
    runtime.server.close();
  }
}

/**
 * Run PHPUnit tests in WordPress Playground environment
 *
 * @param config - Test configuration or path to config file
 * @param streamingReporter - Optional streaming reporter for real-time output
 * @returns CTRF report with test results
 */
export async function runPhpUnitTests(
  config: WPTesterConfig | string,
  streamingReporter?: StreamingReporter
): Promise<Report> {
  // Resolve config (loads from path if string, resolves paths)
  const resolvedConfig = await resolveConfig(config);

  // Check if PHPUnit tests are configured
  if (!shouldRunPhpUnitTests(resolvedConfig)) {
    return Promise.resolve(EMPTY_REPORT);
  }

  // Get PHPUnit config path from resolved config (already absolute after resolveConfig)
  const hostPhpunitConfigPath = resolvedConfig.tests.phpunit!.configPath;

  // Verify the config file exists
  try {
    await access(hostPhpunitConfigPath);
  } catch {
    console.error(`PHPUnit config file not found: ${hostPhpunitConfigPath}`);
    return Promise.resolve(EMPTY_REPORT);
  }

  // Run tests for all environments
  const reports: Report[] = [];
  for (const environment of resolvedConfig.environments) {
    const report = await runPhpUnitTestsForEnvironment(
      resolvedConfig,
      environment,
      hostPhpunitConfigPath,
      streamingReporter
    );
    if (report.results.summary.tests > 0) {
      reports.push(report);
    }
  }

  // Return empty report if no tests ran
  if (reports.length === 0) {
    return EMPTY_REPORT;
  }

  // Return single report as-is, or merge multiple reports
  if (reports.length === 1) {
    return reports[0];
  }

  // Import mergeReports for multiple environments
  return mergeReports(reports);
}
