import { describe, it, expect, beforeAll } from 'vitest';
import { getSchemaPath } from '../src/index';
import { readFileSync } from 'fs';
import Ajv from 'ajv';

describe('Schema - testMode validation', () => {
  let ajv: Ajv;
  let schema: unknown;

  beforeAll(() => {
    // Load the schema
    const schemaPath = getSchemaPath();
    const schemaContent = readFileSync(schemaPath, 'utf-8');
    schema = JSON.parse(schemaContent);

    // Initialize Ajv
    ajv = new Ajv({
      allErrors: true,
      strict: false // Disable strict mode for schema generated by typescript-json-schema
    });
  });

  describe('valid testMode values', () => {
    it('accepts "unit" testMode', () => {
      const config = {
        environments: [
          {
            blueprint: {
              preferredVersions: {
                php: '8.0',
                wp: 'latest'
              }
            }
          }
        ],
        tests: {
          phpunit: {
            phpunitPath: '/path/to/phpunit',
            configPath: '/path/to/config',
            testMode: 'unit'
          }
        }
      };

      const validate = ajv.compile(schema);
      const valid = validate(config);

      expect(valid).toBe(true);
      expect(validate.errors).toBeNull();
    });

    it('accepts "integration" testMode', () => {
      const config = {
        environments: [
          {
            blueprint: {
              preferredVersions: {
                php: '8.0',
                wp: 'latest'
              }
            }
          }
        ],
        tests: {
          phpunit: {
            phpunitPath: '/path/to/phpunit',
            configPath: '/path/to/config',
            testMode: 'integration'
          }
        }
      };

      const validate = ajv.compile(schema);
      const valid = validate(config);

      expect(valid).toBe(true);
      expect(validate.errors).toBeNull();
    });

    it('accepts config without testMode (optional field)', () => {
      const config = {
        environments: [
          {
            blueprint: {
              preferredVersions: {
                php: '8.0',
                wp: 'latest'
              }
            }
          }
        ],
        tests: {
          phpunit: {
            phpunitPath: '/path/to/phpunit',
            configPath: '/path/to/config'
          }
        }
      };

      const validate = ajv.compile(schema);
      const valid = validate(config);

      expect(valid).toBe(true);
      expect(validate.errors).toBeNull();
    });
  });

  describe('invalid testMode values', () => {
    it('rejects invalid testMode value', () => {
      const config = {
        environments: [
          {
            blueprint: {
              preferredVersions: {
                php: '8.0',
                wp: 'latest'
              }
            }
          }
        ],
        tests: {
          phpunit: {
            phpunitPath: '/path/to/phpunit',
            configPath: '/path/to/config',
            testMode: 'invalid-mode'
          }
        }
      };

      const validate = ajv.compile(schema);
      const valid = validate(config);

      expect(valid).toBe(false);
      expect(validate.errors).not.toBeNull();

      // Check that the error is about the enum constraint
      const testModeError = validate.errors?.find(
        err => err.instancePath.includes('testMode') && err.keyword === 'enum'
      );
      expect(testModeError).toBeDefined();
      expect(testModeError?.params).toHaveProperty('allowedValues');
      expect(testModeError?.params.allowedValues).toContain('unit');
      expect(testModeError?.params.allowedValues).toContain('integration');
    });

    it('rejects testMode with wrong type (number)', () => {
      const config = {
        environments: [
          {
            blueprint: {
              preferredVersions: {
                php: '8.0',
                wp: 'latest'
              }
            }
          }
        ],
        tests: {
          phpunit: {
            phpunitPath: '/path/to/phpunit',
            configPath: '/path/to/config',
            testMode: 123
          }
        }
      };

      const validate = ajv.compile(schema);
      const valid = validate(config);

      expect(valid).toBe(false);
      expect(validate.errors).not.toBeNull();

      // Check that the error is about type
      const testModeError = validate.errors?.find(
        err => err.instancePath.includes('testMode')
      );
      expect(testModeError).toBeDefined();
    });

    it('rejects testMode with wrong type (boolean)', () => {
      const config = {
        environments: [
          {
            blueprint: {
              preferredVersions: {
                php: '8.0',
                wp: 'latest'
              }
            }
          }
        ],
        tests: {
          phpunit: {
            phpunitPath: '/path/to/phpunit',
            configPath: '/path/to/config',
            testMode: true
          }
        }
      };

      const validate = ajv.compile(schema);
      const valid = validate(config);

      expect(valid).toBe(false);
      expect(validate.errors).not.toBeNull();
    });
  });

  describe('testMode schema properties', () => {
    it('has correct enum values in schema definition', () => {
      // Navigate to the PHPUnitConfig definition in the schema
      const phpunitConfigDefinition = schema.definitions?.PHPUnitConfig;
      expect(phpunitConfigDefinition).toBeDefined();

      const testModeProperty = phpunitConfigDefinition.properties?.testMode;
      expect(testModeProperty).toBeDefined();
      expect(testModeProperty.type).toBe('string');
      expect(testModeProperty.enum).toContain('unit');
      expect(testModeProperty.enum).toContain('integration');
      expect(testModeProperty.default).toBe('unit');
      expect(testModeProperty.description).toBeDefined();
      expect(testModeProperty.description).toContain('Test mode');
    });
  });
});
